#!/usr/bin/env python3
"""
Compact off-chain Bitcoin oracle service

Primary mode:
  - read local Bitcoin blk*.dat files;
  - reconstruct a simple UTXO set;
  - compute BTC balances per address;
  - listen for LendingPool.BitcoinLiquidityCheckRequested events;
  - update BitcoinOracle.setBtcBalance(...).

Fallback mode:
  - if no blk*.dat files are available, load balances from a JSON file.
  - this keeps the demo executable when the assignment materials do not include
    Bitcoin block files.

Run from hardhat/:

  python3 oracle/oracle_service.py --from-block latest

Scan past requests once:

  python3 oracle/oracle_service.py --from-block 0 --once

Rebuild blk.dat cache:

  python3 oracle/oracle_service.py --rebuild-cache --once

Dependencies:

  python3 -m pip install web3 eth-account python-bitcoinlib
"""

from __future__ import annotations

import argparse
import io
import json
import time
from decimal import Decimal
from pathlib import Path
from typing import Any, Dict, Iterable, Optional, Tuple

from eth_account import Account
from eth_account.signers.local import LocalAccount
from web3 import Web3


SETUP_FILE = "deployments/initial_setup.json"
CHAINDATA_DIR = "../chaindata"
CACHE_FILE = "../data/btc_balances_from_blk_cache.json"
FALLBACK_BALANCES_FILE = "../data/btc_balances.json"

# ARTIFACTS indicates where to find the JSON files generated by Hardhat after the contracts are compiled
ARTIFACTS = {
    "LendingPool": "artifacts/contracts/LendingPool.sol/LendingPool.json",
    "BitcoinOracle": "artifacts/contracts/BitcoinOracle.sol/BitcoinOracle.json",
}

SATOSHI_PER_BTC = 100_000_000
DEFAULT_MAX_BLOCKS = 131_000


# ---------------------------------------------------------------------------
# Generic helpers
# ---------------------------------------------------------------------------

# Reads a JSON file and transforms it into a Python dictionary
def load_json(path: Path) -> Dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"File not found: {path}")

    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


# Saves a Python dictionary in a JSON file
def save_json(path: Path, data: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2), encoding="utf-8")


# Converts from wei to ETH
def wei_to_eth(value: int) -> Decimal:
    return Web3.from_wei(value, "ether")


# Converts from satoshi to BTC
def satoshi_to_btc(value: int) -> Decimal:
    return Decimal(value) / Decimal(SATOSHI_PER_BTC)


# Formats BTC balance for printing
def fmt_sat(value: int) -> str:
    return f"{value} satoshi ({satoshi_to_btc(value)} BTC)"


# Recovers the signed transaction in raw format
def raw_signed_transaction(signed: Any) -> bytes:
    return getattr(signed, "rawTransaction", None) or getattr(signed, "raw_transaction")


# Adds middleware needed to interact with local private chains
def install_poa_middleware(w3: Web3) -> None:
    try:
        from web3.middleware import ExtraDataToPOAMiddleware

        w3.middleware_onion.inject(ExtraDataToPOAMiddleware, layer=0)
    except Exception:
        try:
            from web3.middleware import geth_poa_middleware

            w3.middleware_onion.inject(geth_poa_middleware, layer=0)
        except Exception:
            pass


# Takes the private key from initial_setup.json and creates a Web3 account to sign transactions
def account_from_setup(setup: Dict[str, Any], name: str) -> LocalAccount:
    return Account.from_key(setup["accounts"][name]["private_key"])


# Creates a Web3 object starting from the address and the ABI of the contract
def contract_from_artifact(w3: Web3, name: str, address: str) -> Any:
    artifact = load_json(Path(ARTIFACTS[name]))

    return w3.eth.contract(
        address=Web3.to_checksum_address(address),
        abi=artifact["abi"],
    )


# Builds, signs and sends an Ethereum transaction
def send_tx(
    w3: Web3,
    chain_id: int,
    account: LocalAccount,
    function_call: Any,
    label: str,
    value: int = 0,
) -> Any:
    
    # Building the transaction
    tx = function_call.build_transaction(
        {
            "from": account.address,
            "nonce": w3.eth.get_transaction_count(account.address),
            "chainId": chain_id,
            "gasPrice": w3.eth.gas_price,
            "value": value,
        }
    )

    # Estimates gas cost
    tx["gas"] = int(w3.eth.estimate_gas(tx) * 1.25)

    # Signs the transaction
    signed = Account.sign_transaction(tx, account.key)

    # Sends the transaction
    tx_hash = w3.eth.send_raw_transaction(raw_signed_transaction(signed))

    # Waiting for the transaction to be mined
    receipt = w3.eth.wait_for_transaction_receipt(tx_hash)

    if receipt.status != 1:
        raise RuntimeError(f"{label} failed: {tx_hash.hex()}")

    print(f"{label:<34} tx={tx_hash.hex()} gasUsed={receipt.gasUsed}")
    return receipt


# ---------------------------------------------------------------------------
# BTC balance sources
# ---------------------------------------------------------------------------

# Reads demo BTC balances from JSON and returns a map, or raises an error if a balance is negative (when blk data is not available)
# Instead of recreating the real balance by reading the Bitcoin blockchain, it reads predefined balances
def load_fallback_balances(path: Path) -> Dict[str, int]:
    if not path.exists():
        return {}

    data = load_json(path)
    raw = data.get("balances", data)

    balances: Dict[str, int] = {}

    for address, value in raw.items():
        balance = int(value)

        if balance < 0:
            raise ValueError(f"Negative BTC balance for {address}: {balance}")

        balances[str(address)] = balance

    return balances


# load_cache and save_cache are useful to avoid loading blk*.dat every time. They save a cache file
def load_cache(path: Path) -> Dict[str, int]:
    data = load_json(path)
    raw = data.get("balances", data)

    return {
        str(address): int(balance)
        for address, balance in raw.items()
        if int(balance) > 0
    }


def save_cache(path: Path, balances: Dict[str, int], stats: Dict[str, int]) -> None:
    save_json(
        path,
        {
            "source": "blk.dat",
            "unit": "satoshi",
            "stats": stats,
            "balances": balances,
        },
    )


# Prepares python-bitcoinlib to read Bitcoin data correctly
def select_bitcoin_params(network: str) -> Tuple[Any, Any, Any]:

    # Imports necessary items
    try:
        from bitcoin import SelectParams
        from bitcoin.core import CBlock, b2lx
        from bitcoin.wallet import CBitcoinAddress
    except ImportError as exc:
        raise ImportError(
            "python-bitcoinlib is required for blk.dat parsing.\n"
            "Install it with: python3 -m pip install python-bitcoinlib"
        ) from exc

    # Selects the correct network
    # Bitcoin has multiple networks with different addresses
    # mainnet: real local Bitcoin network
    # testnet: public test network
    # regtest: local test network
    SelectParams(network)

    # Returns classes and functions for parsing
    # CBlock: deserializes a raw Bitcoin block
    # b2lx: converts Bitcoin binary hashes into readable strings
    # CBitcoinAddress: Obtains a Bitcoin address from an output script
    return CBlock, b2lx, CBitcoinAddress


# Tries to return an address from a scriptPubKey
def extract_address(script_pub_key: Any, CBitcoinAddress: Any) -> Optional[str]:  # Optional means that it can be a string or None
    try:
        return str(CBitcoinAddress.from_scriptPubKey(script_pub_key))
    except Exception:
        return None


# Reads a blk file; every block has the following structure:
# magic bytes | size | payload

# Reads 4 magic bytes, then 4 size bytes, then a payload of size bytes
# Returns the payload
def iter_blk_payloads(path: Path) -> Iterable[bytes]:
    with path.open("rb") as f:
        while True:
            magic = f.read(4) # Magic bytes identify the type or format of data (e.g., a Bitcoin block in a specific network)

            if not magic:
                return

            raw_size = f.read(4)

            if len(raw_size) != 4:
                return

            size = int.from_bytes(raw_size, "little")

            if size <= 0:
                return

            payload = f.read(size)

            if len(payload) != size:
                return

            yield payload


# Builds BTC balances starting from the blocks
# For each block, for each transaction:
# Removes old spent outputs
# Adds newly created outputs
def build_balances_from_blk(
    chaindata: Path,
    bitcoin_network: str,
    max_blocks: int,
) -> Tuple[Dict[str, int], Dict[str, int]]: # Returns two dictionaries: balances and stats
    CBlock, b2lx, CBitcoinAddress = select_bitcoin_params(bitcoin_network)

    blk_files = sorted(chaindata.glob("blk*.dat"))

    if not blk_files:
        raise FileNotFoundError(f"No blk*.dat files found in {chaindata}")

    # balances: address -> total balance in satoshi
    balances: Dict[str, int] = {}

    # utxos: (txid, output_index) -> (address, amount)
    utxos: Dict[Tuple[str, int], Tuple[str, int]] = {}

    # stats tracks parsing statistics for debugging and cache metadata
    stats = {
        "blocks": 0,
        "transactions": 0,
        "outputs_indexed": 0,
        "outputs_spent": 0,
        "outputs_skipped": 0,
    }

    print(f"Parsing {len(blk_files)} blk*.dat file(s) from {chaindata}")

    # For each blk*.dat file
    # With enumerate, it obtains file_index and the blk_file path
    for file_index, blk_file in enumerate(blk_files, start=1):
        print(f"[{file_index}/{len(blk_files)}] {blk_file}")

        # Extracts each serialized block payload from the blk.dat file.
        for payload in iter_blk_payloads(blk_file):
            if max_blocks > 0 and stats["blocks"] >= max_blocks:
                print(f"Reached max block limit: {max_blocks}")
                balances = {
                    address: balance
                    for address, balance in balances.items()
                    if balance > 0
                }
                return balances, stats

            try:
                block = CBlock.stream_deserialize(io.BytesIO(payload))
            # Skip malformed or unreadable block payloads
            except Exception:
                stats["outputs_skipped"] += 1
                continue

            stats["blocks"] += 1

            # For each block.vtx (list of block transactions)
            for tx in block.vtx:
                stats["transactions"] += 1

                # Mark spent outputs
                for txin in tx.vin:
                    key = (b2lx(txin.prevout.hash), int(txin.prevout.n))

                    if key in utxos:
                        address, amount = utxos.pop(key)
                        balances[address] = balances.get(address, 0) - amount
                        stats["outputs_spent"] += 1

                        if balances[address] <= 0:
                            balances.pop(address, None)

                txid = b2lx(tx.GetHash())

                # Index new standard outputs
                for output_index, txout in enumerate(tx.vout):
                    amount = int(txout.nValue)
                    address = extract_address(txout.scriptPubKey, CBitcoinAddress)

                    if amount <= 0 or address is None:
                        stats["outputs_skipped"] += 1
                        continue
                    
                    # For each output of the transaction:
                    # Finds amount
                    # Finds the address
                    # If it's valid, adds UTXO
                    # Updates balance
                    utxos[(txid, output_index)] = (address, amount)
                    balances[address] = balances.get(address, 0) + amount
                    stats["outputs_indexed"] += 1

    balances = {
        address: balance
        for address, balance in balances.items()
        if balance > 0
    }

    return balances, stats


# Decides how to build balances. If there are blk files, builds them from those files; otherwise, uses JSON
def load_or_build_balances(args: argparse.Namespace) -> Dict[str, int]:
    # Takes paths from the command line
    chaindata = Path(args.chaindata)
    cache = Path(args.cache)
    fallback = Path(args.fallback_balances)

    # Checks if the folder chaindata exists and if it contains blk*.dat files
    has_blk_files = chaindata.exists() and bool(list(chaindata.glob("blk*.dat")))

    # Reuses cached balances if available, unless rebuilding was requested.
    if has_blk_files:
        if cache.exists() and not args.rebuild_cache:
            print(f"Loading cached BTC balances from {cache}")
            balances = load_cache(cache)

        # If no cache exists, or --rebuild-cache was passed, parse blk*.dat files again
        else:
            balances, stats = build_balances_from_blk(
                chaindata=chaindata,
                bitcoin_network=args.bitcoin_network,
                max_blocks=args.max_blocks,
            )

            # Stores the computed balances so future runs can avoid reparsing blk*.dat files
            save_cache(cache, balances, stats)
            print(f"Saved BTC balance cache to {cache}")
            print(f"Stats: {stats}")

        print(f"Loaded {len(balances)} BTC balances from blk.dat/cache")
        return balances

    balances = load_fallback_balances(fallback)

    # If there are no blk*.dat files and no fallback balances, there are no sources from which to obtain Bitcoin balances
    if not balances:
        raise FileNotFoundError(
            f"No blk*.dat files found in {chaindata} and no fallback balances found in {fallback}"
        )

    print(
        f"No blk*.dat files found in {chaindata}.\n"
        f"Using fallback balances from {fallback}.\n"
        "This validates the oracle event/update flow, but not real blk.dat parsing."
    )
    print(f"Loaded {len(balances)} fallback BTC balances")

    return balances


# ---------------------------------------------------------------------------
# Oracle event loop
# ---------------------------------------------------------------------------

# Converts --from-block into a concrete block number.
# It accepts two types of input:
# "latest" / "current": uses the current block number
# "<number>": converts the string into a number
def block_number_arg(w3: Web3, value: str) -> int:
    if value in {"latest", "current"}:
        return w3.eth.block_number

    return int(value)


# Reads BitcoinLiquidityCheckRequested events from the LendingPool contract
def get_request_logs(lending_pool: Any, from_block: int, to_block: int) -> list[Any]:
    event = lending_pool.events.BitcoinLiquidityCheckRequested()

    try:
        return event.get_logs(from_block=from_block, to_block=to_block)
    except TypeError:
        return event.get_logs(fromBlock=from_block, toBlock=to_block)


# For each event, creates a unique key to avoid processing it more than once
def event_key(event: Any) -> Tuple[str, int]:
    tx_hash = event["transactionHash"]

    if hasattr(tx_hash, "hex"):
        tx_hash = tx_hash.hex()

    return str(tx_hash), int(event["logIndex"])


# Updates the BitcoinOracle contract
def update_oracle(
    w3: Web3,
    chain_id: int,
    oracle: Any,
    trusted_oracle: LocalAccount,
    btc_address: str,
    balance: int,
    force: bool,
) -> None:
    
    # Checks whether there is already a registered balance
    already_recorded = oracle.functions.hasBtcBalanceRecord(btc_address).call()

    # If it already exists and force is not passed, does not update it
    if already_recorded and not force:
        current = oracle.functions.btcBalanceInSatoshi(btc_address).call()
        print(f"Oracle already recorded {btc_address}: {fmt_sat(current)}")
        return

    # If an update is needed, it sends a transaction
    send_tx(
        w3=w3,
        chain_id=chain_id,
        account=trusted_oracle,
        function_call=oracle.functions.setBtcBalance(btc_address, balance),
        label="BitcoinOracle.setBtcBalance",
    )

    # Reads the equivalent value in wei using the logic of the BitcoinOracle contract
    value_wei = oracle.functions.btcValueInWei(btc_address).call()

    print(f"Oracle updated: {btc_address}")
    print(f"  balance: {fmt_sat(balance)}")
    print(f"  value:   {value_wei} wei ({wei_to_eth(value_wei)} ETH)")


# Scans blocks from from_block to to_block and searches for BitcoinLiquidityCheckRequested
def scan_once(
    w3: Web3,
    chain_id: int,
    lending_pool: Any,
    oracle: Any,
    trusted_oracle: LocalAccount,
    balances: Dict[str, int],
    from_block: int,
    to_block: int,
    processed: set[Tuple[str, int]],
    force: bool,
) -> int:
    if to_block < from_block:
        return from_block

    logs = get_request_logs(lending_pool, from_block, to_block)

    # If it does not find events
    if not logs:
        print(f"No oracle requests from block {from_block} to {to_block}")
        return to_block + 1

    print(f"Found {len(logs)} oracle request(s) from block {from_block} to {to_block}")

    # If there are events
    for event in logs:
        key = event_key(event)

        if key in processed:
            continue

        processed.add(key)

        # Extracts applicant and btc_address
        applicant = event["args"]["applicant"]
        btc_address = event["args"]["btcAddress"]

        # Searches BTC balances (if the address is not in the dataset, it considers the balance 0)
        balance = balances.get(btc_address, 0)

        print("\nBitcoinLiquidityCheckRequested")
        print(f"  applicant:  {applicant}")
        print(f"  btcAddress: {btc_address}")
        print(f"  balance:    {fmt_sat(balance)}")

        update_oracle(
            w3=w3,
            chain_id=chain_id,
            oracle=oracle,
            trusted_oracle=trusted_oracle,
            btc_address=btc_address,
            balance=balance,
            force=force,
        )

    return to_block + 1


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Compact Bitcoin oracle service")

    parser.add_argument("--setup", default=SETUP_FILE)
    parser.add_argument("--chaindata", default=CHAINDATA_DIR)
    parser.add_argument("--cache", default=CACHE_FILE)
    parser.add_argument("--fallback-balances", default=FALLBACK_BALANCES_FILE)
    parser.add_argument("--bitcoin-network", choices=["mainnet", "testnet", "regtest"], default="mainnet")
    parser.add_argument("--rebuild-cache", action="store_true")
    parser.add_argument("--from-block", default="latest") # Starts from the last block
    parser.add_argument("--poll-interval", type=int, default=10)
    parser.add_argument("--once", action="store_true")
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--top", type=int, default=0, help="Print top N BTC balances and continue") # Prints the BTC addresses with the highest balances
    parser.add_argument(
        "--max-blocks",
        type=int,
        default=DEFAULT_MAX_BLOCKS,
        help="Maximum number of Bitcoin blocks to parse from blk*.dat files. Default: 131000.",
    )

    return parser.parse_args()


def main() -> None:
    args = parse_args()

    # Loads initial_setup.json
    setup = load_json(Path(args.setup))

    # Loads or builds BTC balances
    balances = load_or_build_balances(args)

    # args.top is used to print the Bitcoin addresses with the highest balances
    if args.top > 0:
        print(f"\nTop {args.top} balances:")
        for i, (address, balance) in enumerate(
            sorted(balances.items(), key=lambda item: item[1], reverse=True)[: args.top],
            start=1,
        ):
            print(f"{i:>3}. {address:<45} {fmt_sat(balance)}")

    # Reads parameters of the private chain
    rpc_url = setup["network"]["rpc_url"] # url used by Python to connect to the local chain
    chain_id = int(setup["network"]["chain_id"])

    # Connects to the chain
    w3 = Web3(Web3.HTTPProvider(rpc_url))
    install_poa_middleware(w3)

    # Checks connection
    if not w3.is_connected():
        raise ConnectionError(f"Could not connect to {rpc_url}")

    # Checks chain id
    if w3.eth.chain_id != chain_id:
        raise RuntimeError(f"Unexpected chain id {w3.eth.chain_id}, expected {chain_id}")

    # Loads contracts
    lending_pool = contract_from_artifact(
        w3,
        "LendingPool",
        setup["contracts"]["LendingPool"],
    )

    oracle = contract_from_artifact(
        w3,
        "BitcoinOracle",
        setup["contracts"]["BitcoinOracle"],
    )

    # Loads trusted oracle account
    trusted_oracle = account_from_setup(setup, "trustedOracle")

    # Checks that the trusted oracle in the setup file is the same as the one saved in the contract
    onchain_trusted_oracle = oracle.functions.trustedOracle().call()

    if Web3.to_checksum_address(onchain_trusted_oracle) != Web3.to_checksum_address(
        trusted_oracle.address
    ):
        raise RuntimeError("trustedOracle in setup file does not match BitcoinOracle.trustedOracle()")

    print("\nConnected to private chain")
    print(f"RPC URL:       {rpc_url}")
    print(f"Chain ID:      {chain_id}")
    print(f"LendingPool:   {lending_pool.address}")
    print(f"BitcoinOracle: {oracle.address}")
    print(f"trustedOracle: {trusted_oracle.address}")
    print(f"trustedOracle balance: {wei_to_eth(w3.eth.get_balance(trusted_oracle.address))} ETH")

    next_from = block_number_arg(w3, args.from_block)
    processed: set[Tuple[str, int]] = set()

    print("\nOracle service started")
    print(f"Starting from block: {next_from}")

    try:
        while True:
            latest = w3.eth.block_number

            next_from = scan_once(
                w3=w3,
                chain_id=chain_id,
                lending_pool=lending_pool,
                oracle=oracle,
                trusted_oracle=trusted_oracle,
                balances=balances,
                from_block=next_from,
                to_block=latest,
                processed=processed,
                force=args.force,
            )

            if args.once:
                print("\nOne-shot scan completed")
                return

            time.sleep(args.poll_interval)

    except KeyboardInterrupt:
        print("\nOracle service stopped by user.")
        return


if __name__ == "__main__":
    main()
